### ISSUE TITLE
module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by Lucas-Wye** [ibarrond/Pyfhel#103]
```
>>> import Pyfhel
```

```
Traceback (most recent call last):
  File "__init__.pxd", line 882, in numpy.import_array
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/w/lib/anaconda3/lib/python3.8/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
  File "Pyfhel/Pyfhel.pyx", line 28, in init Pyfhel.Pyfhel
  File "__init__.pxd", line 884, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

**Comment by AlexMV12** [comment]
I have the same problem.

**Comment by ibarrond** [comment]
Closing! version 3 of Pyfhel should now require this automatically.

**Comment by Lucas-Wye** [comment]
Thank you.
