### ISSUE TITLE
How to install PyfhelV3 in a fresh venv?

### ISSUE THREAD

**Issue by Murat-U-Saglam** [ibarrond/Pyfhel#113]
**Describe the feature**
Getting started. There is currently 0 working installation instruction.

**Is this feature related to a project/objective? Please describe briefly**
In order to help contribute and utilise the project, appropriate installation instruction will be beneficial to all.

**Comment by coderhard** [comment]
1.  Setup a separate environment to prevent stepping on other versions for other projects
`conda create -n pyfhel pandas numpy matplotlib scikit-learn jupyter seaborn `
# All those packages I would normally install. For sure needed numpy

2.  Change into that conda environment
`conda activate pyfhel`

3.  Clone from the dev branch... since that's the one that has the fixes to SEAL and palisade
`git clone --branch dev --recursive https://github.com/ibarrond/Pyfhel.git`

4.   Change into the now cloned directory
`cd Pyfhel/`

5.  Use pip to install in this local environment from this directory
`pip install .`

**Comment by coderhard** [comment]
But sadly, the example client server demo code no longer works with the `dev` build! :(
1. The arguments to contextGen() changed. 
2. Once you by trial and error figure out the right arguments to include (you hope), the HE.savepublicKey(pk_file) throws an error
`AttributeError: 'Pyfhel.Pyfhel.Pyfhel' object has no attribute 'savepublicKey'`

**Comment by Murat-U-Saglam** [comment]
I have tried to install with the method mentioned up above. 
However when I try to import Pyfhel or even run the tests it breaks. 
The following is the error that I get:
```bash
ImportError: /home/muratsaglam/anaconda3/envs/pyfhel/lib/python3.9/site-packages/Pyfhel/./libAfhel.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```
I thought it was due to my C++ compiler for python. However, after running:
```py
import sys

print(sys.version)
```
I noticed I had the appropriate version
```bash
3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
```

**Comment by AlexMV12** [comment]
> I just fixed a lot of pending issues in PyfhelV3 and updated the Demos. Please try it out now!

Hello ibarrond,
Thanks for the great work! I have been closely following the development.

Unfortunately installation fails in a fresh env (both with Python 3.8 and Python 3.10). I'll leave here the log, I just thought to re-use this issue. I can open a new one if you want.

```
pip install Pyfhel
Collecting Pyfhel
  Using cached Pyfhel-3.1.2.tar.gz (40.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.20
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Building wheels for collected packages: Pyfhel
  Building wheel for Pyfhel (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pyfhel (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [175 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_clib
      building 'SEAL' cmake-based library
      -- Build type (CMAKE_BUILD_TYPE): Release
      -- The CXX compiler identification is GNU 12.1.0
      -- The C compiler identification is GNU 12.1.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Microsoft SEAL debug mode: OFF
      -- SEAL_USE_CXX17: ON
      -- SEAL_BUILD_DEPS: ON
      -- SEAL_USE_MSGSL: ON
      -- Microsoft GSL: download ...
      -- Found Git: /usr/bin/git (found version "2.36.1")
      -- SEAL_USE_ZLIB: ON
      -- ZLIB: download ...
      CMake Deprecation Warning at thirdparty/zlib-src/CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Looking for sys/types.h
      -- Looking for sys/types.h - found
      -- Looking for stdint.h
      -- Looking for stdint.h - found
      -- Looking for stddef.h
      -- Looking for stddef.h - found
      -- Check size of off64_t
      -- Check size of off64_t - done
      -- Looking for fseeko
      -- Looking for fseeko - found
      -- Looking for unistd.h
      -- Looking for unistd.h - found
      -- Renaming
      --     /tmp/pip-install-fxl0lext/pyfhel_69b864c419754c23be5b6e35349486ed/Pyfhel/backend/SEAL/thirdparty/zlib-src/zconf.h
      -- to 'zconf.h.included' because this file is included with zlib
      -- but CMake generates it automatically in the build directory.
      -- SEAL_USE_ZSTD: ON
      -- Zstandard: download ...
      CMake Deprecation Warning at thirdparty/zstd-src/build/cmake/CMakeLists.txt:10 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- ZSTD VERSION: 1.4.5
      -- Performing Test CXX_FLAG_STD_CPLUSPLUS11
      -- Performing Test CXX_FLAG_STD_CPLUSPLUS11 - Success
      -- Performing Test C_FLAG_STD_C99
      -- Performing Test C_FLAG_STD_C99 - Success
      -- Performing Test C_FLAG_WALL
      -- Performing Test C_FLAG_WALL - Success
      -- Performing Test CXX_FLAG_WALL
      -- Performing Test CXX_FLAG_WALL - Success
      -- Performing Test C_FLAG_WEXTRA
      -- Performing Test C_FLAG_WEXTRA - Success
      -- Performing Test CXX_FLAG_WEXTRA
      -- Performing Test CXX_FLAG_WEXTRA - Success
      -- Performing Test C_FLAG_WUNDEF
      -- Performing Test C_FLAG_WUNDEF - Success
      -- Performing Test CXX_FLAG_WUNDEF
      -- Performing Test CXX_FLAG_WUNDEF - Success
      -- Performing Test C_FLAG_WSHADOW
      -- Performing Test C_FLAG_WSHADOW - Success
      -- Performing Test CXX_FLAG_WSHADOW
      -- Performing Test CXX_FLAG_WSHADOW - Success
      -- Performing Test C_FLAG_WCAST_ALIGN
      -- Performing Test C_FLAG_WCAST_ALIGN - Success
      -- Performing Test CXX_FLAG_WCAST_ALIGN
      -- Performing Test CXX_FLAG_WCAST_ALIGN - Success
      -- Performing Test C_FLAG_WCAST_QUAL
      -- Performing Test C_FLAG_WCAST_QUAL - Success
      -- Performing Test CXX_FLAG_WCAST_QUAL
      -- Performing Test CXX_FLAG_WCAST_QUAL - Success
      -- Performing Test C_FLAG_WSTRICT_PROTOTYPES
      -- Performing Test C_FLAG_WSTRICT_PROTOTYPES - Success
      -- CMAKE_INSTALL_PREFIX: /usr/local
      -- CMAKE_INSTALL_LIBDIR: lib
      -- ZSTD_LEGACY_SUPPORT not defined!
      -- ZSTD_MULTITHREAD_SUPPORT is disabled
      -- SEAL_USE_INTEL_HEXL: OFF
      -- BUILD_SHARED_LIBS: OFF
      -- SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT: ON
      -- SEAL_USE_GAUSSIAN_NOISE: OFF
      -- SEAL_DEFAULT_PRNG: Blake2xb
      -- x86intrin.h - found
      -- SEAL_USE_INTRIN: ON
      -- Performing Test SEAL_MEMSET_S_FOUND
      -- Performing Test SEAL_MEMSET_S_FOUND - Failed
      -- Looking for explicit_bzero
      -- Looking for explicit_bzero - found
      -- Looking for explicit_memset
      -- Looking for explicit_memset - not found
      -- SEAL_USE_MEMSET_S: OFF
      -- SEAL_USE_EXPLICIT_BZERO: ON
      -- SEAL_USE_EXPLICIT_MEMSET: OFF
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- SEAL_BUILD_SEAL_C: OFF
      -- SEAL_BUILD_EXAMPLES: OFF
      -- SEAL_BUILD_TESTS: OFF
      -- SEAL_BUILD_BENCH: OFF
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-fxl0lext/pyfhel_69b864c419754c23be5b6e35349486ed/build/temp.linux-x86_64-3.8/Pyfhel/SEAL
      Traceback (most recent call last):
        File "/home/ale/Repos/Pyfhel/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/ale/Repos/Pyfhel/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ale/Repos/Pyfhel/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 639, in <module>
          setup(
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0rm2kapg/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_clib.py", line 115, in run
          self.build_libraries(self.libraries)
        File "setup.py", line 285, in build_libraries
          self.build_cmake_lib(lib_name, build_info)
        File "setup.py", line 320, in build_cmake_lib
          self.run_cmake_cli(source_dir, build_dir)
        File "setup.py", line 488, in run_cmake_cli
          run_command(['cmake', '--build',  '.', '-j', str(n_jobs)] +\
        File "setup.py", line 140, in run_command
          process = subprocess.Popen(
        File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.8/subprocess.py", line 1580, in _execute_child
          executable = args[0]
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pyfhel
Failed to build Pyfhel
ERROR: Could not build wheels for Pyfhel, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the '/home/ale/Repos/Pyfhel/venv/bin/python3.8 -m pip install --upgrade pip' command.
```

**Comment by ibarrond** [comment]
Ooh, found the small mistake! just missing `()`. Fixing and updating now.

**Comment by AlexMV12** [comment]
> Ooh, found the small mistake! just missing `()`. Fixing and updating now.

Yup, I confirm now it works. Thanks!

**Comment by ibarrond** [comment]
Closing, since `Pyfhel==3.1` seems to be installing and passing tests correctly both in Windows and Linux!
