### ISSUE TITLE
Failed decoding with CKKS: `'utf-8' codec can't decode byte 0xe5 in position 0: unexpected end of data`

### ISSUE THREAD

**Issue by AlexMV12** [ibarrond/Pyfhel#130]
**Description**
Decoding fails using the CKKS scheme.

**Code To Reproduce Error**
```python
from Pyfhel import Pyfhel

HE = Pyfhel()
HE.contextGen(scheme='ckks', n=16384, scale=2**30, qi=[60]+[30]*7+[60])
HE.keyGen()
HE.relinKeyGen()

ptxt1 = HE.encode(42.0)
print(f"Decoded -> {HE.decode(ptxt1)}")
```
produces:
```
Traceback (most recent call last):
  File "prova2.py", line 9, in <module>
    print(f"Decoded -> {HE.decode(ptxt1)}")
  File "Pyfhel/Pyfhel.pyx", line 852, in Pyfhel.Pyfhel.Pyfhel.decode
  File "Pyfhel/Pyfhel.pyx", line 801, in Pyfhel.Pyfhel.Pyfhel.decodeFrac
  File "<__array_function__ internals>", line 180, in copy
  File "/omitted/venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 935, in copy
    return array(a, order=order, subok=subok, copy=True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 0: unexpected end of data
```

**Expected behavior**
It should work. :) 

**Setup:**
 - OS: Ubuntu 20.04 LTS
 - Python: 3.8.10
 - C compiler version: GCC 9.4.0
 - Pyfhel Version: last commit

**Comment by ibarrond** [comment]
Running it now produces the correct result: `Decoded -> [42. 42. 42. ... 42. 42. 42.]`
