### ISSUE TITLE
How to set the ckks parameter to achieve the smallest ciphertext size

### ISSUE THREAD

**Issue by napoay** [ibarrond/Pyfhel#149]
I only need to encrypt and sum up `k` one-dimensional floating-point vectors. The maximum length of the vector is 2000. How can I set the ckks parameter to achieve the smallest ciphertext size?

```
import numpy as np
from Pyfhel import Pyfhel

HE = Pyfhel()           # Creating empty Pyfhel object
ckks_params = {
    'scheme': 'CKKS',   # can also be 'ckks'
    'n': 2**11,         # Polynomial modulus degree. For CKKS, n/2 values can be
                        #  encoded in a single ciphertext. 
                        #  Typ. 2^D for D in [10, 16]
    'scale': 2**30,     # All the encodings will use it for float->fixed point
                        #  conversion: x_fix = round(x_float * scale)
                        #  You can use this as default scale or use a different
                        #  scale on each operation (set in HE.encryptFrac)
    'qi_sizes': [60, 30, 30, 30, 60] # Number of bits of each prime in the chain. 
                        # Intermediate values should be  close to log2(scale)
                        # for each operation, to have small rounding errors.
}
HE.contextGen(**ckks_params)  # Generate context for bfv scheme
HE.keyGen()             # Key Generation: generates a pair of public/secret keys
HE.rotateKeyGen()


arr_x = np.random.random(2000)

ptxt_x = HE.encodeFrac(arr_x)   # Creates a PyPtxt plaintext with the encoded arr_x

ctxt_x = HE.encryptPtxt(ptxt_x) # Encrypts the plaintext ptxt_x and returns a PyCtxt

```
I set n to 2**11 and then encrypt the array but get the following error: 
```
ValueError: encryption parameters are not set correctly
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.keyGen'
ValueError: encryption parameters are not set correctly
RuntimeError: <Afseal>: Context not initialized
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.rotateKeyGen'
RuntimeError: <Afseal>: Context not initialized
Traceback (most recent call last):
  File "a.py", line 25, in <module>
    ptxt_x = HE.encodeFrac(arr_x)   # Creates a PyPtxt plaintext with the encoded arr_x
  File "Pyfhel/Pyfhel.pyx", line 688, in Pyfhel.Pyfhel.Pyfhel.encodeFrac
  File "Pyfhel/Pyfhel.pyx", line 707, in Pyfhel.Pyfhel.Pyfhel.encodeFrac
RuntimeError: <Afseal>: CKKS context not initialized


```

**Comment by AlexanderViand** [comment]
Try to not specify the `qi_sizes`. The ones in your example are too large for `n = 2**11`, so it's better to let SEAL choose them appropriately for that `n`.

**Comment by napoay** [comment]
> Try to not specify the `qi_sizes`. The ones in your example are too large for `n = 2**11`, so it's better to let SEAL choose them appropriately for that `n`.

Pyfhel does not allow not setting `qi_size`.

```
AssertionError: CKKS scheme requires a list of prime sizes (qi_sizes) or primes (qi) to be set
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.contextGen'
AssertionError: CKKS scheme requires a list of prime sizes (qi_sizes) or primes (qi) to be set
RuntimeError: <Afseal>: Context not initialized
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.keyGen'
RuntimeError: <Afseal>: Context not initialized
RuntimeError: <Afseal>: Context not initialized
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.rotateKeyGen'
RuntimeError: <Afseal>: Context not initialized
Traceback (most recent call last):
  File "Demo_3_ckks.py", line 62, in <module>
    ptxt_x = HE.encodeFrac(arr_x)   # Creates a PyPtxt plaintext with the encoded arr_x
  File "Pyfhel/Pyfhel.pyx", line 688, in Pyfhel.Pyfhel.Pyfhel.encodeFrac
  File "Pyfhel/Pyfhel.pyx", line 704, in Pyfhel.Pyfhel.Pyfhel.encodeFrac
  File "Pyfhel/PyPtxt.pyx", line 43, in Pyfhel.PyPtxt.PyPtxt.__cinit__
RuntimeError: <Afseal>: Context not initialized

```

**Comment by ibarrond** [comment]
Let's write the entire operation you wish to compute:

```python
import numpy as np
from Pyfhel import Pyfhel

# Initialize Pyfhel
HE = Pyfhel()           # Creating empty Pyfhel object
ckks_params = {'scheme': 'CKKS', 'n': 2**12,  'scale': 2**30,  'qi_sizes': [30, 30, 30]}
status = HE.contextGen(**ckks_params)  # Generate context for ckks scheme
print(status)            # Should print 'sucess: valid' if everything is OK. Otherwise the `keyGen` and `rotateKeyGen` ops will raise exceptions.
HE.keyGen()             # Key Generation: generates a pair of public/secret keys
HE.rotateKeyGen()

# Generate data
k = 1000
np.random.seed(42)
arr_x = np.random.random((2000, k))

# Operate: add all ciphertexts and all slots.
ctxt_rows_x = [HE.encryptFrac(row_x) for row_x in arr_x] # Encrypt each row of arr_x
ctxt_colsum = sum(ctxt_rows_x)                                      # Sum all ciphertexts into one
ctxt_sum    = (+ctxt_colsum)                                           # Uses `HE.cumul_add` to sum the slots of ctxt_colsum using log2(n) rotations and additions

# Check result
expected   = arr_x.sum()
interm_res = HE.decrypt(ctxt_rowsum).sum()
result        = HE.decrypt(ctxt_sum)[0]

print(f"Expected:     {expected}")
print(f"intermediate: {interm_res}")
print(f"result:       {result}")
```

**Comment by napoay** [comment]
> Let's write the entire operation you wish to compute:
> 
> ```python
> import numpy as np
> from Pyfhel import Pyfhel
> 
> # Initialize Pyfhel
> HE = Pyfhel()
> ckks_params = {'scheme': 'CKKS', 'n': 2**12,  'scale': 2**30,  'qi_sizes': [30, 30, 30]}
> status = HE.contextGen(**ckks_params)  # Generate context for ckks scheme
> print(status)            # Should print 'sucess: valid' if everything is OK. Otherwise the `keyGen` and `rotateKeyGen` ops will raise exceptions.
> HE.keyGen()
> HE.rotateKeyGen()
> 
> # Generate data
> k = 1000
> np.random.seed(42)
> arr_x = np.random.random((2000, k))
> 
> # Operate: add all ciphertexts and all slots.
> ctxt_rows_x = [HE.encryptFrac(row_x) for row_x in arr_x] # Encrypt each row of arr_x
> ctxt_colsum = sum(ctxt_rows_x)  # Sum all ciphertexts into one
> ctxt_sum    = (+ctxt_colsum)    # Uses `HE.cumul_add` to sum the slots of ctxt_colsum using log2(n) rotations and additions
> 
> # Check result
> expected   = arr_x.sum()
> interm_res = HE.decrypt(ctxt_rowsum).sum()
> result     = HE.decrypt(ctxt_sum)[0]
> 
> print(f"Expected:     {expected}")
> print(f"intermediate: {interm_res}")
> print(f"result:       {result}")
> ```
> 
> You can play with different parameter sets, validating both the parameter set and the result of the operation you wish to perform.

Thanks a bunch for your detailed answer, it's helped me a lot!

**Comment by napoay** [comment]
#177
