### ISSUE TITLE
TypeError on Install: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by evangronberg** [ibarrond/Pyfhel#161]
**Description**
Pyfhel won't install. See the console output below.

**Code To Reproduce Error**
```
pip install Pyfhel
```

**Setup:**
 - OS: Windows 10
 - Python: 3.7.9
 - C compiler version: MSC v.1900 64 bit (AMD64)
 - Pyfhel Version: N/A

**Console Output**

```
(.venv) C:\Python\fhe-fl-gossip-architecture>pip install Pyfhel 
Collecting Pyfhel
  Using cached Pyfhel-3.3.1.tar.gz (48.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.21
  Using cached numpy-1.21.0-cp37-cp37m-win_amd64.whl (13.9 MB)
Building wheels for collected packages: Pyfhel
  Building wheel for Pyfhel (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pyfhel (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.7
      creating build\lib.win-amd64-3.7\Pyfhel
      copying Pyfhel\__init__.py -> build\lib.win-amd64-3.7\Pyfhel
      creating build\lib.win-amd64-3.7\Pyfhel\utils
      copying Pyfhel\utils\Backend_t.py -> build\lib.win-amd64-3.7\Pyfhel\utils
      copying Pyfhel\utils\Scheme_t.py -> build\lib.win-amd64-3.7\Pyfhel\utils
      copying Pyfhel\utils\utils.py -> build\lib.win-amd64-3.7\Pyfhel\utils
      copying Pyfhel\utils\__init__.py -> build\lib.win-amd64-3.7\Pyfhel\utils
      running build_clib
      building 'SEAL' cmake-based library
      Traceback (most recent call last):
        File "C:\Python\fhe-fl-gossip-architecture\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Python\fhe-fl-gossip-architecture\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Python\fhe-fl-gossip-architecture\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 250, in build_wheel
          metadata_directory)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\build_meta.py", line 245, in build_wheel
          wheel_directory, config_settings)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 689, in <module>
          'build_clib' : SuperBuildClib},
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\GRONBE~1\AppData\Local\Temp\1\pip-build-env-8dyh3no1\overlay\Lib\site-packages\setuptools\_distutils\command\build_clib.py", line 115, in run
          self.build_libraries(self.libraries)
        File "setup.py", line 294, in build_libraries
          self.build_cmake_lib(lib_name, build_info)
        File "setup.py", line 330, in build_cmake_lib
          self.run_cmake_cli(source_dir, build_dir, cmake_opts)
        File "setup.py", line 500, in run_cmake_cli
          , cwd=build_dir)
        File "setup.py", line 151, in run_command
          **kwargs,
        File "c:\program files\python37\lib\subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "c:\program files\python37\lib\subprocess.py", line 1148, in _execute_child
          args = list2cmdline(args)
        File "c:\program files\python37\lib\subprocess.py", line 555, in list2cmdline
          needquote = (" " in arg) or ("\t" in arg) or not arg
      TypeError: argument of type 'WindowsPath' is not iterable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pyfhel
Failed to build Pyfhel
ERROR: Could not build wheels for Pyfhel, which is required to install pyproject.toml-based projects
```

**Comment by ibarrond** [comment]
Related to #157, it seems to be a known bug of Python3.7 in Windows. You
can:
- Upgrade to Python3.8+ to make it disappear.
- Apply the patch listed in #157 yourself, thus installing Pyfhel from the
GitHub repository.

**Comment by evangronberg** [comment]
That worked! Thanks for your help, I greatly appreciate it. :D
