### ISSUE TITLE
Hi! I have a problem about installation.

### ISSUE THREAD

**Issue by xymshry** [ibarrond/Pyfhel#190]
Hi! What I want to ask is: 
if I modify the file ( pyproject.toml ), to set the  
```c++
SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT
```
to OFF,  should I use the command 
```python
pip install .
``` 
or I have to use the command  
```python
pip install -e .
``` 
 for installation?  
Because I succeed install it with the command 'pip install .',  and I use the command 
```python
pip show Pyfhel
``` 
it print
```python
Name: Pyfhel
Version: 3.4.1
Summary: Python for Homomorphic Encryption Libraries
Home-page: https://pyfhel.readthedocs.io
Author: Alberto Ibarrondo, Alexander Viand
Author-email: ibarrond@eurecom.fr, alexander.viand@inf.ethz.ch
License: GNU GPLv3
Location: /home/**/VIR/TH/lib/python3.8/site-packages
Requires: numpy
Required-by:
``` 
, but! I I go to the python interface and Enter the command
```python
>>> import Pyfhel
```  
it shows 
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/**/Pyfhel/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ModuleNotFoundError: No module named 'Pyfhel.Pyfhel'
``` 
I'm wondering if I didn't use the command 'pip install -e .' to install Pyfhel after modifying the pyproject.toml file.
So I install it again with the command ' pip install -e .', and it shows to me that
```python
Obtaining file:///home/**/Pyfhel
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.21 in /home/eamon/VIR/TH/lib/python3.8/site-packages (from Pyfhel==3.4.1) (1.24.2)
Installing collected packages: Pyfhel
  Attempting uninstall: Pyfhel
    Found existing installation: Pyfhel 3.4.1
    Uninstalling Pyfhel-3.4.1:
      Successfully uninstalled Pyfhel-3.4.1
  Running setup.py develop for Pyfhel
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [25 lines of output]
        running develop
        running egg_info
        writing Pyfhel.egg-info/PKG-INFO
        writing dependency_links to Pyfhel.egg-info/dependency_links.txt
        writing requirements to Pyfhel.egg-info/requires.txt
        writing top-level names to Pyfhel.egg-info/top_level.txt
        cimporting numpy version '1.24.3'
        reading manifest file 'Pyfhel.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        /tmp/pip-build-env-1yv4oyim/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:160: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /tmp/pip-build-env-1yv4oyim/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        warning: no previously-included files matching 'Pyfhel/backend/palisade/**' found anywhere in distribution
        adding license file 'LICENSE.txt'
        writing manifest file 'Pyfhel.egg-info/SOURCES.txt'
        running build_ext
        cimporting numpy version '1.24.3'
        building 'Pyfhel.Pyfhel' extension
        x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__PYX_ENUM_CLASS_DECL=enum -IPyfhel/Afhel -I/home/eamon/VIR/TH/include -I/usr/include/python3.8 -I/tmp/pip-build-env-1yv4oyim/overlay/lib/python3.8/site-packages/numpy/core/include -c Pyfhel/Pyfhel.cpp -o build/temp.linux-x86_64-3.8/Pyfhel/Pyfhel.o -std=c++17 -O3 -fopenmp
        Pyfhel/Pyfhel.cpp:1148:10: fatal error: seal/plaintext.h: No such file or directory.
         #include "seal/plaintext.h"
                  ^~~~~~~~~~~~~~~~~~
        compilation terminated.
        error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of Pyfhel
  Moving to /home/eamon/VIR/TH/lib/python3.8/site-packages/Pyfhel-3.4.1.dist-info/
   from /home/eamon/VIR/TH/lib/python3.8/site-packages/~yfhel-3.4.1.dist-info
  Moving to /home/eamon/VIR/TH/lib/python3.8/site-packages/Pyfhel/
   from /home/eamon/VIR/TH/lib/python3.8/site-packages/~yfhel
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [25 lines of output]
    running develop
    running egg_info
    writing Pyfhel.egg-info/PKG-INFO
    writing dependency_links to Pyfhel.egg-info/dependency_links.txt
    writing requirements to Pyfhel.egg-info/requires.txt
    writing top-level names to Pyfhel.egg-info/top_level.txt
    cimporting numpy version '1.24.3'
    reading manifest file 'Pyfhel.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /tmp/pip-build-env-1yv4oyim/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:160: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /tmp/pip-build-env-1yv4oyim/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    warning: no previously-included files matching 'Pyfhel/backend/palisade/**' found anywhere in distribution
    adding license file 'LICENSE.txt'
    writing manifest file 'Pyfhel.egg-info/SOURCES.txt'
    running build_ext
    cimporting numpy version '1.24.3'
    building 'Pyfhel.Pyfhel' extension
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__PYX_ENUM_CLASS_DECL=enum -IPyfhel/Afhel -I/home/eamon/VIR/TH/include -I/usr/include/python3.8 -I/tmp/pip-build-env-1yv4oyim/overlay/lib/python3.8/site-packages/numpy/core/include -c Pyfhel/Pyfhel.cpp -o build/temp.linux-x86_64-3.8/Pyfhel/Pyfhel.o -std=c++17 -O3 -fopenmp
    Pyfhel/Pyfhel.cpp:1148:10: fatal error: seal/plaintext.h: No such file or directory.
     #include "seal/plaintext.h"
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1 -> 23.1.1
[notice] To update, run: pip install --upgrade pip

``` 
Others, I always use virtualenv （python 3.8）to Run these instructions.
I didn't find an answer to this question and don't know what I should do below.
I hope you can understand my question and provide an answer, thank you very much!

**Comment by ibarrond** [comment]
The first error seems to be associated to #51 . Exit the root folder of Pyfhel to run anything related to it.

The second error, `fatal error: seal/plaintext.h: No such file or directory`, is related to #150 , and it is caused by a missing repository cloning. In the [README.md instructions](https://github.com/ibarrond/Pyfhel#install--uninstall) it is written that you should clone the repository with the `--recursive` flag to ensure it downloads SEAL too.

**Comment by xymshry** [comment]
Hi, ibarrond!
About the first error, I do wonder about the situation (There is also a file with the same name called Pyfhel under the Pyfhel file). But， I don't understand what you say (Just run python3 ANYWHERE ELSE (otherwise Python gets confused between your installed package and the subfolder Pyfhel which has a __init__.py).) in #51 . Can you explain the problem, thanks.

About the second error, I have already used the instruction (--recurisve)  before I asked this question, but it still happened.

**Comment by ibarrond** [comment]
@xymshry I mean that, once you install Pyfhel from source (cloning the github repo), do not run your Python scripts/programs/notebooks/consoles inside the folder that contains the cloned repository (the `Pyfhel` folder containing the `README.md` and the `setup.py`). Just go to any other folder in your computer.

On the second issue, do not install it with the `-e` flag, just do `pip install .`

**Comment by ibarrond** [comment]
Closing due to inactivity. Feel free to reopen if needed.

**Comment by qqaatw** [comment]
@ibarrond could you please explain why `pip install -e .` doesn't work?

**Comment by ibarrond** [comment]
@qqaatw it has to do with the folder structure (too many things called `Pyfhel` around). I'm planning to solve it alongside some other recent install errors sometime soon.
