### ISSUE TITLE
Executing multiple moltiplication with ckks without falling into scale error

### ISSUE THREAD

**Issue by CastreseRiccio** [ibarrond/Pyfhel#201]
Hi everyone.

I'm facing a little dilemma, I'm using an implementation of CKKS schema with this parameters:

`ckks_params = {'scheme':schema, 'n': 2**14, 'scale': 2**40, 'qi_sizes': [60, 40, 40, 40, 40, 40, 40, 40, 60]}`

And trying to do multiple moltiplication (more than 5/6) with this function: 

```
def homomorphic_product(*ctxts):
    if len(ctxts) < 2:
        raise ValueError("homomorphic_product requires at least two arguments.")
    ctxt_1 = _encode_sent_byte(ctxts[0])
    ctxt_2 = _encode_sent_byte(ctxts[1])
    he_manager._he.align_mod_n_scale(ctxt_1, ctxt_2)
    total = he_manager._he.multiply(ctxt_1, ctxt_2)
    for ctxt in ctxts[2:]:
        temp_ctxt = _encode_sent_byte(ctxt)
        he_manager._he.align_mod_n_scale(total, temp_ctxt)
        total = he_manager._he.multiply(total, temp_ctxt)
    return total.to_bytes().hex()
```
The moltiplication works fine until i use more than 6 factors, in which case I'm stuck with this error:

**Traceback (most recent call last):
  File "/home/ubuntu/python_workspace/squirrel/test_change_schema.py", line 37, in <module>
    p1 = facade.product(a,b,c,d,e,a,b,c,d,e,a,b,c,d,e)
  File "/home/ubuntu/python_workspace/squirrel/squirrellib/facade.py", line 59, in product
    return he_manager.homomorphic_product(*ctxt_bytes_list)
  File "/home/ubuntu/python_workspace/squirrel/squirrellib/he_manager.py", line 167, in homomorphic_product
    total = he_manager._he.multiply(total, temp_ctxt)
  File "Pyfhel/Pyfhel.pyx", line 1176, in Pyfhel.Pyfhel.Pyfhel.multiply
  File "Pyfhel/Pyfhel.pyx", line 1201, in Pyfhel.Pyfhel.Pyfhel.multiply
ValueError: scale out of bounds**

Any idea?

**Comment by AlexanderViand** [comment]
This doesn't seem that surprising, given that your parameters should support around 6-7 multiplications in a row. 

However, if you were to change your code a bit, you should be able to use that to multiply up to $2^6$ - $2^7$ elements! 
Instead of a simple for loop that sequentially computes $((((((a_1 * a_2) * a_3 ) * a_4) * a_5) * a_6) * a_7)$, i.e., six multiplications in a sequence, you can instead compute this as a "tree" $( (a_1 * a_2) * (a_2 * a_3) ) \ * ((a_4 * a_5) * (a_6 * a_7))$ and suddenly, there are only _three_ multiplications in sequence.

Writing code to do this correctly for an arbitrary number of factors is not too hard, but also somewhat fiddly and annoying. Therefore, a lot fo FHE libraries actually provide a function `multiply_many` that does this already. I know SEAL has one, and I'd be surprised if Palisade/openFHE didn't offer one, too. So maybe Pyfhel could expose these to users? (@ibarrond)

**Comment by CastreseRiccio** [comment]
Yeah I tried to not be too lumpsy with the ckks parameters to not loose too much precision. Even using the scale alignment is not solving the issue. the multyply_many will be the perfect solution if avaiable. However your code change is equally worth trying. Thank you for the answer @AlexanderViand

**Comment by CastreseRiccio** [comment]
@AlexanderViand 
I tried your advice updating the method like this:

```
def homomorphic_product(*ctxts):
    if len(ctxts) < 2:
        raise ValueError("homomorphic_product requires at least two arguments.")
    elements = [_encode_sent_byte(ctxt) for ctxt in ctxts]
    num_multiplications = len(elements) - 1
    if num_multiplications <= 0:
        raise ValueError("homomorphic_product requires at least two arguments.")
    total = elements[0]
    for i in range(1, len(elements)):
        total = total * elements[i]
    return total.to_bytes().hex()
```

but the results are the same, even with 6 factor the error is:


```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/python_workspace/squirrel/test_change_schema.py", line 38, in <module>
    p_test = facade.product(uno, uno, uno, uno, uno, uno, uno, uno, uno, uno, uno, uno)
  File "/home/ubuntu/python_workspace/squirrel/squirrellib/facade.py", line 59, in product
    return he_manager.homomorphic_product(*ctxt_bytes_list)
  File "/home/ubuntu/python_workspace/squirrel/squirrellib/he_manager.py", line 166, in homomorphic_product
    total = total * elements[i]
  File "Pyfhel/PyCtxt.pyx", line 466, in Pyfhel.PyCtxt.PyCtxt.__mul__
  File "Pyfhel/Pyfhel.pyx", line 1201, in Pyfhel.Pyfhel.Pyfhel.multiply
ValueError: scale out of bounds
```

Any idea? even if there are some ckks_params configuration that can allow at least 9/10 multiplications losing some accuracy could be enough for me

**Comment by AlexanderViand** [comment]
Ah, right! I didn't notice this in your initial code snippet, but you're not relinearizing and rescaling after the multiplications, which you need to be doing!

I recommend you look at the [CKKS example](https://github.com/ibarrond/Pyfhel/blob/master/examples/Demo_3_Float_CKKS.py) and read the [Pyfhel paper](https://dl.acm.org/doi/pdf/10.1145/3474366.3486923)? That should explain what this is and when&why it's necessary.
