### ISSUE TITLE
ValueError: encrypted_ntt and plain_ntt parameter mismatch in evaluate_polynomial

### ISSUE THREAD

**Issue by kamzon** [ibarrond/Pyfhel#224]
**Description:**
I encountered a `ValueError` while using the Pyfhel library in the `evaluate_polynomial` function. The error specifically points to a parameter mismatch between `encrypted_ntt` and `plain_ntt`. The issue arises when attempting to perform certain operations within the function.
**Code Issue:**
/encry_minimaxcompa.py:63: UserWarning: Cannot align scales 0 and 30 (available rescalings: [])
  monomial = monomial * coeff
Traceback (most recent call last):
  File encry_minimaxcompa.py", line 108, in <module>
    c_result = MinimaxComp(encrypted_a, encrypted_b, alpha, epsilon, depth, margin, HE)
  File "encry_minimaxcompa.py", line 20, in MinimaxComp
    result = evaluate_polynomial(p, c_x, HE)
  File "//encry_minimaxcompa.py", line 63, in evaluate_polynomial
    monomial = monomial * coeff
  File "Pyfhel/PyCtxt.pyx", line 468, in Pyfhel.PyCtxt.PyCtxt.__mul__
  File "Pyfhel/Pyfhel.pyx", line 1224, in Pyfhel.Pyfhel.Pyfhel.multiply_plain
ValueError: encrypted_ntt and plain_ntt parameter mismatch

**Code Snippet:**
```python
def evaluate_polynomial(coefficients, ctxt_x, HE):
    c_result = []
    HE.relinKeyGen()
    for i, coeff in enumerate([1,1,1]):
        if i == 0:
            monomial = HE.encrypt(1)
        else:
            monomial = ctxt_x
            HE.rescale_to_next(monomial)
            HE.relinKeyGen()
            monomial = ~monomial
            for j in range(1, i):
                monomial = monomial * ctxt_x
                HE.rescale_to_next(monomial)
                HE.relinKeyGen()
                monomial = ~monomial
        HE.relinKeyGen()
        monomial = monomial * coeff
        HE.rescale_to_next(monomial)
        HE.relinKeyGen()
        HE.relinearize(monomial)
        monomial = ~monomial
        c_result.append(monomial)
    return c_result

**Comment by ibarrond** [comment]
@kamzon It looks like you ran out of available rescalings. Try adding more moduli to the `qi` in the ContextGen parameters, one per rescaling.
