### ISSUE TITLE
Not able to install Pyfhel module in Windows 10

### ISSUE THREAD

**Issue by cyber-titan** [ibarrond/Pyfhel#228]
**Description**
I am trying to install Pyfhel module in Windows 10 laptop but I am facing some error.

**Setup:**
 - OS: Windows10
 - Python: Python 3.11.3
 - C compiler version: [MSC v.1934 64 bit (AMD64)]
 - Pyfhel Version: 3.4.2

**Error (output when I used pip install Pyfhel):**
Collecting Pyfhel
  Using cached Pyfhel-3.4.2.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      Compiling Pyfhel\Pyfhel.pyx because it changed.
      Compiling Pyfhel\PyCtxt.pyx because it changed.
      Compiling Pyfhel\PyPtxt.pyx because it changed.
      Compiling Pyfhel\PyPoly.pyx because it changed.
      [1/4] Cythonizing Pyfhel\PyCtxt.pyx
      [2/4] Cythonizing Pyfhel\PyPoly.pyx
      [3/4] Cythonizing Pyfhel\PyPtxt.pyx
      [4/4] Cythonizing Pyfhel\Pyfhel.pyx
      running egg_info
      writing Pyfhel.egg-info\PKG-INFO
      writing dependency_links to Pyfhel.egg-info\dependency_links.txt
      writing requirements to Pyfhel.egg-info\requires.txt
      writing top-level names to Pyfhel.egg-info\top_level.txt
      cimporting numpy version '1.26.4'
      reading manifest file 'Pyfhel.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\hp\OneDrive\Desktop\private-major-menu-based-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\hp\OneDrive\Desktop\private-major-menu-based-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\OneDrive\Desktop\private-major-menu-based-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel   
          return self._get_build_requires(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 666, in <module>
          setup(
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
          self.find_sources()
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
          mm.run()
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 540, in run
          self.add_defaults()
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 584, in add_defaults
          self.read_manifest()
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\command\sdist.py", line 195, in read_manifest
          self.filelist.append(line)
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 482, in append
          path = convert_path(item)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-onxdkfj7\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 128, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/alberto.ibarrondo/Technocracy/workspace/Pyfhel/Pyfhel/Afhel/Afseal.cpp' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ibarrond** [comment]
Hmmm, this is a new one. In the meantime, you can install it in your system using WSL

**Comment by cyber-titan** [comment]
Ok

**Comment by ShaneKosieradzki** [comment]
bump.

unable to install on windows 11 for py 3.9, 3.10, 3.11

**Comment by CHAOSV177** [comment]
`  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Compiling Pyfhel\Pyfhel.pyx because it changed.
      Compiling Pyfhel\PyCtxt.pyx because it changed.
      Compiling Pyfhel\PyPtxt.pyx because it changed.
      Compiling Pyfhel\PyPoly.pyx because it changed.
      [1/4] Cythonizing Pyfhel\PyCtxt.pyx
      [2/4] Cythonizing Pyfhel\PyPoly.pyx
      [3/4] Cythonizing Pyfhel\PyPtxt.pyx
      [4/4] Cythonizing Pyfhel\Pyfhel.pyx
      running egg_info
      writing Pyfhel.egg-info\PKG-INFO
      writing dependency_links to Pyfhel.egg-info\dependency_links.txt
      writing requirements to Pyfhel.egg-info\requires.txt
      writing top-level names to Pyfhel.egg-info\top_level.txt
      cimporting numpy version '1.24.4'
      reading manifest file 'Pyfhel.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel     
          return hook(config_settings)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_
wheel
          return self._get_build_requires(
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires    
          self.run_setup()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 666, in <module>
          setup(
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands      
          dist.run_commands()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands      
          self.run_command(cmd)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command       
          cmd_obj.run()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
          self.find_sources()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources     
          mm.run()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 540, in run

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
`

**Comment by CHAOSV177** [comment]
`  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Compiling Pyfhel\Pyfhel.pyx because it changed.
      Compiling Pyfhel\PyCtxt.pyx because it changed.
      Compiling Pyfhel\PyPtxt.pyx because it changed.
      Compiling Pyfhel\PyPoly.pyx because it changed.
      [1/4] Cythonizing Pyfhel\PyCtxt.pyx
      [2/4] Cythonizing Pyfhel\PyPoly.pyx
      [3/4] Cythonizing Pyfhel\PyPtxt.pyx
      [4/4] Cythonizing Pyfhel\Pyfhel.pyx
      running egg_info
      writing Pyfhel.egg-info\PKG-INFO
      writing dependency_links to Pyfhel.egg-info\dependency_links.txt
      writing requirements to Pyfhel.egg-info\requires.txt
      writing top-level names to Pyfhel.egg-info\top_level.txt
      cimporting numpy version '1.24.4'
      reading manifest file 'Pyfhel.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel     
          return hook(config_settings)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_
wheel
          return self._get_build_requires(
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires    
          self.run_setup()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 666, in <module>
          setup(
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands      
          dist.run_commands()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands      
          self.run_command(cmd)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command       
          cmd_obj.run()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
          self.find_sources()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources     
          mm.run()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 540, in run

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
`

**Comment by CHAOSV177** [comment]
`  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Compiling Pyfhel\Pyfhel.pyx because it changed.
      Compiling Pyfhel\PyCtxt.pyx because it changed.
      Compiling Pyfhel\PyPtxt.pyx because it changed.
      Compiling Pyfhel\PyPoly.pyx because it changed.
      [1/4] Cythonizing Pyfhel\PyCtxt.pyx
      [2/4] Cythonizing Pyfhel\PyPoly.pyx
      [3/4] Cythonizing Pyfhel\PyPtxt.pyx
      [4/4] Cythonizing Pyfhel\Pyfhel.pyx
      running egg_info
      writing Pyfhel.egg-info\PKG-INFO
      writing dependency_links to Pyfhel.egg-info\dependency_links.txt
      writing requirements to Pyfhel.egg-info\requires.txt
      writing top-level names to Pyfhel.egg-info\top_level.txt
      cimporting numpy version '1.24.4'
      reading manifest file 'Pyfhel.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\anaconda\envs\pycrcnn\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel     
          return hook(config_settings)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_
wheel
          return self._get_build_requires(
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires    
          self.run_setup()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 666, in <module>
          setup(
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands      
          dist.run_commands()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands      
          self.run_command(cmd)
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command       
          cmd_obj.run()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
          self.find_sources()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources     
          mm.run()
        File "C:\Users\61431\AppData\Local\Temp\pip-build-env-5fh2mzvk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 540, in run

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
`

**Comment by theundertakerjr666** [comment]
curious why that value is hardcoded :
File "C:\Users\admin\AppData\Local\Temp\pip-build-env-m7l7tcdu\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 128, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/alberto.ibarrondo/Technocracy/workspace/Pyfhel/Pyfhel/Afhel/Afseal.cpp' cannot be absolute
      [end of output]

**Comment by ibarrond** [comment]
Hopefully v3.4.3 solved it. Otherwise please reopen!
