### ISSUE TITLE
pip Pyfhel went wrong

### ISSUE THREAD

**Issue by chiehyi1207** [ibarrond/Pyfhel#232]
python 3.11
OS:window 11
I have already install Microsoft C++(does it need to add to path)
I got below when i pip install Pyfthe

C:\Users\chieh>pip install Pyfhel
Collecting Pyfhel
  Downloading Pyfhel-3.4.2.tar.gz (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 5.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      Compiling Pyfhel\Pyfhel.pyx because it changed.
      Compiling Pyfhel\PyCtxt.pyx because it changed.
      Compiling Pyfhel\PyPtxt.pyx because it changed.
      Compiling Pyfhel\PyPoly.pyx because it changed.
      [1/4] Cythonizing Pyfhel\PyCtxt.pyx
      [2/4] Cythonizing Pyfhel\PyPoly.pyx
      [3/4] Cythonizing Pyfhel\PyPtxt.pyx
      [4/4] Cythonizing Pyfhel\Pyfhel.pyx
      running egg_info
      writing Pyfhel.egg-info\PKG-INFO
      writing dependency_links to Pyfhel.egg-info\dependency_links.txt
      writing requirements to Pyfhel.egg-info\requires.txt
      writing top-level names to Pyfhel.egg-info\top_level.txt
      cimporting numpy version '1.26.4'
      reading manifest file 'Pyfhel.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 666, in <module>
          setup(
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
          self.find_sources()
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
          mm.run()
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 540, in run
          self.add_defaults()
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 584, in add_defaults
          self.read_manifest()
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\command\sdist.py", line 195, in read_manifest
          self.filelist.append(line)
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 482, in append
          path = convert_path(item)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-vtqepg6i\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 128, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/alberto.ibarrondo/Technocracy/workspace/Pyfhel/Pyfhel/Afhel/Afseal.cpp' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by chiehyi1207** [comment]
I upgrade my python to 3.12
but still get the following problem

C:\Users\chieh>pip install pyfhel
Collecting pyfhel
  Using cached Pyfhel-3.4.2.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chieh\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-j9_n7y75\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-j9_n7y75\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\chieh\AppData\Local\Temp\pip-build-env-j9_n7y75\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2178, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Shakemilktea** [comment]
I solve the problem by using GIT BASH, run:
```
git clone --recursive https://github.com/ibarrond/Pyfhel.git
pip install .
```
Hope this can help you.

**Comment by Ronhar1** [comment]
From the looks of it, they stored a dependency in their own user directory and then told the package to look in THEIR user directory for the dependency. How did that pass the unit tests?
all they needed to do is say the dependency exits in ./someDirectory instead of /Users/alberto,ibarrondo/[...]

**Comment by Lambika** [comment]
> I solve the problem by using GIT BASH, run:
> 
> ```
> git clone --recursive https://github.com/ibarrond/Pyfhel.git
> pip install .
> ```
> 
> Hope this can help you.

It still doesn't solve the problem. :(

**Comment by NadaAdelIsmailM** [comment]
@Lambika hope this helps
git clone --recursive https://github.com/ibarrond/Pyfhel.git
%cd Pyfhel/
!pip install .

**Comment by ibarrond** [comment]
Hopefully v3.4.3 solved the issue. Otherwise reopen!
