### ISSUE TITLE
ModuleNotFoundError: No module named 'Pyfhel.Pyfhel.Pyfhel'

### ISSUE THREAD

**Issue by lilvmy** [ibarrond/Pyfhel#245]
**Description**
I have installed Pyfhel==3.4.2, but import the Pyfhel leads an error ModuleNotFoundError: No module named 'Pyfhel.Pyfhel.Pyfhel'
**Code To Reproduce Error**
from Pyfhel import Pyfhel

**Expected behavior**
Traceback (most recent call last):
  File "/home/cysren/home/cysren/Desktop/ld_file/Secure-DNN-Inference-with-Adversarial-training/SimpleExample/SimEncryptProcessing.py", line 10, in <module>
    from Pyfhel import Pyfhel
  File "/home/cysren/.virtualenvs/ld_env/lib/python3.8/site-packages/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
  File "/home/cysren/.virtualenvs/ld_env/lib/python3.8/site-packages/Pyfhel/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ModuleNotFoundError: No module named 'Pyfhel.Pyfhel.Pyfhel'

**Setup:**
 - OS: [e.g. Ubuntu]
 - Python: [e.g. 3.8.19]
 - C compiler version: [e.g. gcc 11.4.0 64 bit (nvida), can be easily found between brackets by running `python` in a terminal]
 - Pyfhel Version: [e.g. 3.4.2 --> If lower than latest github repo version, please try that one out first!]

**Comment by ibarrond** [comment]
Please fill all the details above!

**Comment by lilvmy** [comment]
Thank you, I will list these information.

system: Linux version 6.5.0-41-generic (buildd@lcy02-amd64-120) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2

Python version: 3.8.19
C compiler version:  g++ is already the newest version (4:11.2.0-1ubuntu1).
gcc is already the newest version (4:11.2.0-1ubuntu1).

When I use pip install Pyfhel, it does not apper above-mentioned issues

**Comment by ibarrond** [comment]
Please run `gcc -v` to get the gcc version.

**Comment by lilvmy** [comment]
Noted with thanks, the gcc version is  11.4.0

(ld_env) (base) cysren@cysren-Precision-3660:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by ibarrond** [comment]
Hopefully v3.4.3 solved the issue. Otherwise feel free to reopen!
