### ISSUE TITLE
Missing sub-dirs

### ISSUE THREAD

**Issue by lorepieri8** [ibarrond/Pyfhel#41]
```
lorenzo@Lorenzos-Air ~/ghubRepo/Pyfhel $ python3 setup.py build --CYTHONIZE
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    [os.path.join(AFHEL_PATH, 'Afseal.cpp')])
  File "setup.py", line 13, in scan
    for file in os.listdir(dir):
FileNotFoundError: [Errno 2] No such file or directory: 'Pyfhel/SEAL/SEAL/seal'
```

**Comment by ibarrond** [comment]
This can be solved by pulling all the submodules with:

    git submodule update --init --recursive

To avoid it in the first place, make sure you clone the repo with `--recursive`:

    git clone --recursive https://github.com/ibarrond/Pyfhel.git
