### ISSUE TITLE
Error when first import Pyfhel. ModuleNotFoundError: No module named 'Pyfhel.Pyfhel'

### ISSUE THREAD

**Issue by ibarrond** [ibarrond/Pyfhel#51]
I got tired of getting this error, and thus I'm documenting it for my future self.

```python
>>> import Pyfhel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/make/rast/Documents/Pyfhel/Pyfhel/__init__.py", line 1, in <module>
    from .Pyfhel import Pyfhel
ModuleNotFoundError: No module named 'Pyfhel.Pyfhel'
```

**Comment by ibarrond** [comment]
This error happens when you install `Pyfhel` from the cloned repository (e.g.: `pip install .`), you run python3 directly inside the top level of the cloned repository's folder. Just run python3 ANYWHERE ELSE (otherwise Python gets confused between your installed package and the subfolder `Pyfhel` which has a `__init__.py`). Good to keep it in mind!
