### ISSUE TITLE
Windows10 -> ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'

### ISSUE THREAD

**Issue by ibarrond** [ibarrond/Pyfhel#53]
When running the `Demo_Encrypting.py`, result in a Windows10 Python3 is:
```bash
==============================================================
===================== Pyfhel ENCRYPTING ======================
==============================================================
1. Creating Context and KeyGen in a Pyfhel Object
2. Encrypting integers with encryptInt
    Empty created ctxt_i2:  <Pyfhel Ciphertext, encoding=UNDEFINED, size=2>
    int  94 -> ctxt_i1  <Pyfhel Ciphertext, encoding=INTEGER, size=2>
    int  -235 -> ctxt_i2  <Pyfhel Ciphertext, encoding=INTEGER, size=2>
3. Encrypting floating point values with encryptFrac
    float  3.5 -> ctxt_f1  <Pyfhel Ciphertext, encoding=FRACTIONAL, size=2>
    float  -7.8 -> ctxt_f2  <Pyfhel Ciphertext, encoding=FRACTIONAL, size=2>
4. Encrypting lists of integers using batching with encryptBatch
    list  [1, 2, 3, 4, 5, 6] -> ctxt_b1  <Pyfhel Ciphertext, encoding=BATCH, size=2>
    list  [-2, 3, -4, -3, 2, -1] -> ctxt_b2  <Pyfhel Ciphertext, encoding=BATCH, size=2>
5. Encrypting numpy 1D integer vectors using batching encryptArray
Traceback (most recent call last):
  File ".\Demo_Encrypting.py", line 49, in <module>
    ctxt_a1 = HE.encryptArray(array1)   # Encrypting array1 in a new PyCtxt with encryptArray
  File "Pyfhel/Pyfhel.pyx", line 228, in Pyfhel.Pyfhel.Pyfhel.encryptArray
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'
```

Maybe related to https://stackoverflow.com/questions/32262976/cython-buffer-type-mismatch-expected-int-but-got-long?

**Comment by ibarrond** [comment]
13aad80 Solved it
