### ISSUE TITLE
Windows 10 test.py Error when Saving / Reloading ciphertexts

### ISSUE THREAD

**Issue by ibarrond** [ibarrond/Pyfhel#54]
There is something wrong when Saving / Reloading ciphertexts in Windows10 Python3. Full error message:

```bash
======================================================================
ERROR: test_Pyfhel_5d_save_restore_batch (__main__.PyfhelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Pyfhel\Pyfhel.pyx", line 390, in Pyfhel.Pyfhel.Pyfhel.decryptBatch
RuntimeError: <Pyfhel ERROR> wrong encoding type in PyCtxt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..\Pyfhel\test.py", line 424, in test_Pyfhel_5d_save_restore_batch
    self.assertEqual(pyfhel.decryptBatch(loaded)[:4], [1, 2, 3, 4])
SystemError: <method 'decryptBatch' of 'Pyfhel.Pyfhel.Pyfhel' objects> returned a result with an error set

======================================================================
ERROR: test_Pyfhel_5d_save_restore_float (__main__.PyfhelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Pyfhel\Pyfhel.pyx", line 366, in Pyfhel.Pyfhel.Pyfhel.decryptFrac
RuntimeError: <Pyfhel ERROR> wrong encoding type in PyCtxt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..\Pyfhel\test.py", line 408, in test_Pyfhel_5d_save_restore_float
    self.assertEqual(pyfhel.decryptFrac(loaded), 3.125)
SystemError: <method 'decryptFrac' of 'Pyfhel.Pyfhel.Pyfhel' objects> returned a result with an error set

======================================================================
ERROR: test_Pyfhel_5d_save_restore_int (__main__.PyfhelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Pyfhel\Pyfhel.pyx", line 343, in Pyfhel.Pyfhel.Pyfhel.decryptInt
RuntimeError: <Pyfhel ERROR> wrong encoding type in PyCtxt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..\Pyfhel\test.py", line 392, in test_Pyfhel_5d_save_restore_int
    self.assertEqual(pyfhel.decryptInt(loaded), 42)
SystemError: <method 'decryptInt' of 'Pyfhel.Pyfhel.Pyfhel' objects> returned a result with an error set

======================================================================
FAIL: test_Pyfhel_5c_save_restore_all (__main__.PyfhelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "..\Pyfhel\test.py", line 375, in test_Pyfhel_5c_save_restore_all
    pyfhel2.decryptInt(ctxt_restored), 42, "decrypting ciphertext should work"
```

**Comment by ibarrond** [comment]
solved in 73434f1a8dd3a3bcf7ab8941a65a349ae428d92b
