### ISSUE TITLE
Accessing and Utilizing Underlying Homomorphic Encryption Parameters

### ISSUE THREAD

**Issue by QuickSort7** [ibarrond/Pyfhel#97]
I installed Pyfhel by using the pip tool and have a few questions.

Does the Pyfhel library currently allow users to access the underlying cryptographic objects/values such as tangible forms of the generated public keys and private keys as well as perform standard Python operations on these objects/values (e.g. list operations, arithmetic, etc.)?

Can the bytes for the public/secret keys returned by the to_bytes_publicKey() and to_bytes_privateKey() methods be utilized in encryption and decryption tasks and perform standard Python operations on these objects/values (e.g. list operations, arithmetic, etc.)?

Please advise. Thank you very much.

**Comment by ibarrond** [comment]
Hi @QuickSort7 , on your first question: we're currently working on a low level access to the polynomials behind plaintexts, ciphertexts and public/private keys. Stay tuned for it, as it will allow arithmetic operations on the coefficients of these polynomials, which will take the form of vectors (1D arrays or lists) of complex values,

I'm not sure I understand your second question fully, but I have the feeling the answer is No. The `bytes` object returned by these two serialization functions is completely custom-made, and it will only work with Pyfhel or with the original SEAL; you should use them to save/send them somewhere else and load the key/s by calling the appropriate `from_bytes_...` function with that same `bytes` obj.

**Comment by QuickSort7** [comment]
Hello @ibarrond, thank you for responding. Is there a projected window for when users will be able to access the low level polynomials behind plaintexts, ciphertexts, and public/private keys?

When the public/private key bytes are recovered with either from_bytes() function, is it possible to encrypt/decrypt data with segments of these bytes by utilizing Pyfhel's existing API functions?

Thank you.

**Comment by ibarrond** [comment]
We are finally releasing Pyfhel v3 in beta mode (`pip install Pyfhel==3.0.0b3` for the most up-to-date), which allows access to underlying polynomials of plaintexts (`HE.poly_from_plaintext(ptxt)`) and ciphertexts (`HE.poly_from_ciphertext(ctxt, i)` for poly in position `i`). public and secret keys will have to wait a bit more.

**Comment by Crypto-201** [comment]
I tried to install this but below error occurred.



Collecting Pyfhel==3.0.0b3
  Downloading Pyfhel-3.0.0b3.tar.gz (42.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 MB 2.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      Compiling C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\Pyfhel.pyx because it changed.
      Compiling C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\PyCtxt.pyx because it changed.
      Compiling C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\PyPtxt.pyx because it changed.
      Compiling C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\PyPoly.pyx because it changed.
      [1/4] Cythonizing C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\PyCtxt.pyx
      [2/4] Cythonizing C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\PyPoly.pyx
      [3/4] Cythonizing C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\PyPtxt.pyx
      [4/4] Cythonizing C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-install-jbjq0xdx\pyfhel_b1153b6b911240499d454504c8fa5324\Pyfhel\Pyfhel.pyx
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
     
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
     
      DESCRIPTION:
          `Project license <https://www.python.org/dev/peps/pep-0621/#license>`_.
     
      GIVEN VALUE:
          "GNU GPLv3"
     
      OFFENDING RULE: 'oneOf'
     
      DEFINITION:
          {
              "oneOf": [
                  {
                      "properties": {
                          "file": {
                              "type": "string",
                              "$$description": [
                                  "Relative path to the file (UTF-8) which contains the license for the",
                                  "project."
                              ]
                          }
                      },
                      "required": [
                          "file"
                      ]
                  },
                  {
                      "properties": {
                          "text": {
                              "type": "string",
                              "$$description": [
                                  "The license of the project whose meaning is that of the",
                                  "`License field from the core metadata",
                                  "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                              ]
                          }
                      },
                      "required": [
                          "text"
                      ]
                  }
              ]
          }
      Traceback (most recent call last):
        File "C:\Users\AFTAB AKRAM\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\AFTAB AKRAM\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\AFTAB AKRAM\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 540, in <module>
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\dist.py", line 868, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 62, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 126, in read_configuration
          validate(subset, filepath)
        File "C:\Users\AFTAB AKRAM\AppData\Local\Temp\pip-build-env-ts2uk11b\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 51, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.license`.
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
     
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ibarrond** [comment]
@Crypto-201 install the latest version of `Pyfhel` by just running `pip install Pyfhel`. This should solve the installation issue.
